site_name: 'CompSci Notes'
site_author: 'Chad Sheets'
site_url: 'https://chadsheets.com/notes-compsci/'

docs_dir: 'docs'
theme:
  name: 'rtd-dropdown'

repo_name: 'cjsheets/notes-compsci'
repo_url: 'https://github.com/cjsheets/notes-compsci'
copyright: Copyright &copy; 2017 <a href="http://cjsheets.com">Chad Sheets</a>.

pages:
  - Overview:
      - Intoduction: 'index.md'
  - General:
      - Big-O: 'general/big-o/index.md'
  - Data Structures:
      - List/Queue: 'data-structures/list-queue/index.md'
      - Tree/Tries: 'data-structures/tree/index.md'
#      - Graph: 'data-structures/graph/index.md'
      - Heap: 'data-structures/heap/index.md'
      - Vector: 'data-structures/vector/index.md'
      - Hash Table: 'data-structures/hash-table/index.md'
  - Search:
      - Breadth/Depth First: 'search-algorithms/breadth-depth-first/index.md'
      - Binary Search: 'search-algorithms/binary-search/index.md'
  - Sorting:
      - Introduction: 'sorting-algorithms/index.md'
      - Merge Sort: 'sorting-algorithms/merge-sort/index.md'
      - Quick Sort: 'sorting-algorithms/quick-sort/index.md'
  - Javascript:
      - Basics: 'javascript/basics.md'
  - Interview:
      - Basics: 'interview/index.md'
      - Security: 'interview/security.md'
      - System Design: 'interview/system-design.md'