site_name: 'Computer Science Notes'
pages:
- General:
    - General CompSci: 'general/index.md'
    - Big-O: 'general/big-o/index.md'
- Data Structures:
    - Data Structures: 'general/index.md'
    - List/Queue: 'data-structures/list-queue/index.md'
    - Tree/Tries: 'data-structures/tree/index.md'
    - Graph: 'data-structures/graph/index.md'
    - Heap: 'data-structures/heap/index.md'
    - Vector: 'data-structures/vector/index.md'
    - Hash Table: 'data-structures/hash-table/index.md'
- Search:
    - Search Algorithms: 'general/index.md'
    - Breadth/Depth First: 'search-algorithms/breadth-depth-first/index.md'
    - Binary Search: 'search-algorithms/binary-search/index.md'
- Sorting:
    - Sorting Algorithms: 'sorting-algorithms/index.md'
    - Merge Sort: 'sorting-algorithms/merge-sort/index.md'
    - Quick Sort: 'sorting-algorithms/quick-sort/index.md'
- Javascript:
    - Basics: 'javascript/index.md'
docs_dir: 'docs'
site_dir: 'www'
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  palette:
    primary: 'blue'
    accent: 'light-blue'
  feature:
    tabs: true
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

copyright: Copyright &copy; 2017 <a href="http://cjsheets.com">Chad Sheets</a>.